name: 15-minute-cron
on:
  schedule:
    - cron: '30 */4 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://chatroom-two.vercel.app/api/cron?secret=${{ secrets.CRON_SECRET }}'
